### ISSUE TITLE
base year update

### ISSUE THREAD

**Issue by cahartin** [JGCRI/Hector_COMBO#17]
Is the base year just for discounting costs?

We took the base year as the year SST is relative to.  Do we need to update the SSTs? Should the SSTs be relative to 1850? or relative to 2015? 

I changed the base year from 2007 to 2015 and everything ran fine. 
Use 2007 as base year (default)? n
Enter base year for discounting: 2015

**Comment by abigailsnyder** [comment]
If we update the base year to 2015, then we also will have to update all of the patterns.
The patterns learn how to relate `TOS_local(t) - TOS_local(2007) = a * Tgav(t) + b`

It's not hard to do, but we can't just use the existing patterns+pattern results if we are changing the base year to 2015. 

As far as what COMBO uses the base year for, no clue.

**Comment by cahartin** [comment]
right, i realized we need to update the patterns if we change the base year.  I will do more digging to make sure I'm fully satisfied with what year we pick.  

In COMBO - it's only base year for discounting costs.

**Comment by cahartin** [comment]
The change in temperature is coming from SCENGEN - which can be user specified. The SCENGEN manual picks 1990 as its base year.

I think we should pick another year or range of years for our SST base year (1850-1880 or 1900).

**Comment by abigailsnyder** [comment]
> The change in temperature is coming from SCENGEN - which can be user specified. The SCENGEN manual picks 1990 as its base year.

@cahartin 

But COMBO isn't just generally calling SCENGEN. It's calling specific, pre-run results that from a specific run of SCENGEN that had some selected base year. So I think COMBO is expected deltaSST values that are in units of degC change from the same base year. We need to be giving our deltaSST values as changing from the same base year as the SCENGEN runs for this pairing with COMBO.

edit to add: if the person who designed COMBO to work with SCENGEN assumed that the deltaSST values that come out of SCENGEN are in change from 1990 (default year), then we should be using deltaSST in change from 1990 too.  Unless COMBO can somehow be run without SCENGEN results, where even that implicit specification of deltaSST base year is something truly flexible?

**Comment by cahartin** [comment]
yes exactly. What was the base year coming out of SCENGEN? 1. do we care? 2. if not, let's pick our own base year and be consistent

**Comment by abigailsnyder** [comment]
I can convince myself either way that we care or don't equally well because I have no idea what assumptions COMBO actually makes about the data it uses in most of the scripts. 

The loop warns that the model is sensitive to default deltaT for the first threshold but doesn't given any information about what base year for that deltaT (combo_loopv5.m line 49). This makes me think the base year does matter but I have no idea what it is.


 It's clear that 2007 is the baseline year for discounting (line 118). 
Then on line 138, the code begins defining a startDate and endDate (1950-2010) but doesn't make it clear what those are for; I think the historical data they use to get monthly patterns.

**Comment by abigailsnyder** [comment]
I did some digging; I think this is the paper corresponding to the version of COMBO that we have.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3876994/ 

1. It appears that the projected temperatures are in change from year 2000 - I think we'll be safest if we stay consistent with that. 2000 seems like a fine point to measure from and then we don't have to worry as much about what COMBO assumes about the data it gets. I'm still a little confused as to why the values in the BAU3 2000 files are not 0 though.

2. One novelty is that our work will actually use TOS values - the paper indicates that they actually used TAS values as standins: 
>  Temperatures obtained from SCENGEN are lower-atmosphere temperatures because SSTs are unavailable from the MAGICC/SCENGEN model. However, tests of these predictions against modeled future SST values have shown differences <0.2°C for the locations of interest

**Comment by stephpenn1** [comment]
Ha! Just printed this out!

**Comment by abigailsnyder** [comment]
@cahartin I opened a branch (https://github.com/JGCRI/Hector_COMBO/tree/acs_year2000deltaTOS) where I have updated all of the Scenario files so that the deltaTOS values are calculated relative to the year 2000 instead of 2007 (ie the files here https://github.com/JGCRI/Hector_COMBO/tree/acs_year2000deltaTOS/2012.07.09.COMBO/COMBO/Scengen_EPA). 

I did keep all of the files where we calculated the deltaTOS relative to 2007 (https://github.com/JGCRI/Hector_COMBO/tree/acs_year2000deltaTOS/2012.07.09.COMBO/COMBO/Scengen_EPA/deltaTOS_relative_2007); it might make the most sense to just delete that subdirectory
